# @package _global_
# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
# defaults:
#   - override /hydra/hydra_logging: colorlog
#   - override /hydra/job_logging: colorlog
hydra:
  run:
    dir: ${output_dir}

  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
        mode: a