# path to root directory
# this requires PROJECT_ROOT environment variable to exist

root_dir: /data/yangxianghao/SKEL-CF

data_inputs: ${paths.root_dir}/data_inputs
data_outputs: ${paths.root_dir}/data_outputs
work_dir: ${hydra:runtime.cwd}